pass context when not from global (e.g. ETP cart)
the-events-calendar/event-tickets pull request #1856
Opened 2020-11-06 00:08 UTC by cliffordp

[ETP-472]

2020-11-10 04:31 UTC, sc0ttkclark commented on src/views/v2/tickets/item/content.php
> +$this->template( 'v2/tickets/item/extra', $context );
This shouldn't be necessary, if it is, we should fix it in a future sprint as part of a Common thing. This workaround shouldn't be needed/used.

2020-11-10 04:32 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra.php
> +	<?php $this->template( 'v2/tickets/item/extra/description-toggle', $context ); ?>
This shouldn't be necessary, if it is, we should fix it in a future sprint as part of a Common thing. This workaround shouldn't be needed/used.

2020-11-10 04:32 UTC, sc0ttkclark requested changes
src/views/v2/tickets/item/extra/available.php is good here, but the other two files changed includes code that shouldn't be necessary/used.

2020-11-12 20:46 UTC, cliffordp commented
@sc0ttkclark both ET and ETP tests passing after removing what you said (this PR's most recent commit). There have been many changes to base branch and others' PRs so maybe the reason I did it resolved itself another way 👍 

ET passing:
![image](https://user-images.githubusercontent.com/1812179/98994433-65e49a00-24f5-11eb-99cf-66cefdd9635a.png)

ETP passing
![image](https://user-images.githubusercontent.com/1812179/98994443-69782100-24f5-11eb-966c-d85b9902c74b.png)

**FYI: https://github.com/moderntribe/event-tickets-plus/pull/1087#issuecomment-726312170 was prior to this most recent commit. So both that PR and this PR should be good to merge.**

2020-11-18 02:45 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/available.php
Needs since/version TBD update

2020-11-18 02:45 UTC, sc0ttkclark requested changes
Needs since/version TBD update

2021-03-02 15:53 UTC, closed without merging