support for ETP’s tests
the-events-calendar/event-tickets pull request #1859
Opened 2020-11-10 03:21 UTC by cliffordp

[ETP-471]

2020-11-10 04:27 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra.php
> +	<?php $this->template( 'v2/tickets/item/extra/description-toggle', $context ); ?>
$context should be necessary here

2020-11-10 04:28 UTC, sc0ttkclark commented on src/views/v2/tickets/item/content.php
> +$this->template( 'v2/tickets/item/extra', $context );
None of these changes should be necessary, if they are, let's save whatever the root cause is for a future PR to address it in common.

2020-11-10 04:29 UTC, sc0ttkclark commented on src/Tribe/Tickets_View.php
> +	 * @since TBD Moved getting of context array to its own method.
This is useful, but it's late in the sprint to make this change, we need to workaround it for now until a future sprint

2020-11-10 04:29 UTC, sc0ttkclark requested changes
Some changes here, some stuff to save for a future sprint too

2021-03-02 15:52 UTC, juanfra commented
Closing as the linked PR was no longer relevant https://github.com/the-events-calendar/event-tickets-plus/pull/1089#issuecomment-776018732

2021-03-02 15:52 UTC, closed without merging