Add compatibility to multiple shortcodes in the same page
the-events-calendar/event-tickets pull request #1920
Opened 2021-01-11 21:31 UTC by bordoni

2021-01-11 21:59 UTC, sc0ttkclark requested changes
This looks good, we might want to consider in the future changing the identifier to a class instead of ID for this case.

Needs ticket/changelog

2021-01-12 04:36 UTC, sc0ttkclark commented on readme.txt
> +* Fix - Multiple shortcodes `[tribe_tickets post_id="ID"]` in a single page will now properly work with Modal and adding to cart.
```suggestion
* Fix - Multiple shortcodes `[tribe_tickets post_id="ID"]` on a single page will now properly work with the Attendee Registration Modal and adding to the cart / checking out.
```

2021-01-12 18:17 UTC, bordoni commented
Related to #1921

2021-01-13 22:02 UTC, sc0ttkclark approved these changes

2021-01-13 22:03 UTC, merged