Inverted SQL quotes for MySQL 8.0 compatiblity
the-events-calendar/event-tickets pull request #1952
Opened 2021-02-24 17:52 UTC by rafsuntaskin

[ET-1021]

<img width="627" alt="Screen Shot 2021-02-24 at 11 49 27 PM" src="https://user-images.githubusercontent.com/7523321/109043165-3c91f780-76fb-11eb-9bf7-2107a64a9f98.png">

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Attendee_Repository.php
> +				$optout_keys = "'" . implode( '", "', $optout_keys ) . "'";
Double quotes were still used here.

```suggestion
				$optout_keys = "'" . implode( "', '", $optout_keys ) . "'";
```

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$event_meta_keys = "'" . implode( '", "', $event_meta_keys ) . "'";
Fix double quotes in the implode

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$attendee_types = "'" . implode( '", "', $attendee_types ) . "'";
Fix double quotes in the implode

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$event_meta_keys = "'" . implode( '", "', $event_meta_keys ) . "'";
Fix double quotes in the implode

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$attendee_types = "'" . implode( '", "', $attendee_types ) . "'";
Fix double quotes in the implode

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$event_meta_keys = "'" . implode( '", "', $event_meta_keys ) . "'";
Fix double quotes in the implode

2021-02-24 18:03 UTC, sc0ttkclark commented on src/Tribe/Repositories/Traits/Post_Attendees.php
> +		$event_meta_keys = "'" . implode( '", "', $event_meta_keys ) . "'";
Fix double quotes in the implode

2021-02-24 18:04 UTC, sc0ttkclark requested changes
More double quotes still need to be replaced, specifically in the implode() usage and then we need to add a changelog entry

2021-02-24 20:03 UTC, rafsuntaskin commented
Updated the remaining inverted quotes within `implode` and added Changelog.

2021-02-26 17:56 UTC, sc0ttkclark approved these changes

2021-02-26 17:57 UTC, merged