[ET-982] Aesthetic updates for blocks.
the-events-calendar/event-tickets pull request #1964
Opened 2021-03-09 13:04 UTC by juanfra

[ET-982]
https://www.loom.com/share/50e1525c786e4c07a65579b7723aa1bc

- Adding white background color as asked in the ticket.
- Additionally, I'm adjusting the blocks to be consistent with the new design language of the blocks editor. I guess the negative margins were made when the block editor (at that moment, Gutenberg) was looking different. This can be seen in the demo video.
- Updating the font-family to what we're using on our FE design system for consistency.

2021-03-09 13:06 UTC, juanfra commented
Additionally, I'm cleaning up a bit of the PHP here: https://github.com/the-events-calendar/event-tickets/pull/1965

2021-03-09 17:43 UTC, paulmskim approved these changes

2021-03-10 17:33 UTC, sc0ttkclark approved these changes

2021-03-10 18:19 UTC, sc0ttkclark requested changes
Where's changelog?

2021-03-12 19:21 UTC, sc0ttkclark approved these changes

2021-03-15 08:46 UTC, merged