[ET-1078] Blocks > Fix RSVP & Tickets block description
the-events-calendar/event-tickets pull request #1981
Opened 2021-04-08 11:56 UTC by juanfra

### 🎫 Ticket

[ET-1078] 

### 🗒️ Description

- Switching the tickets and RSVP blocks to have an autosize textarea so it doesn't break the block when using long descriptions.
- Few aesthetics amendments (i.e.: using the design system black)

### 🎥 Artifacts 

https://www.loom.com/share/6c943f7a82034284b134eef49551054a

### ✔️ Checklist
- [x] I've included a readme.txt Changelog entry. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-04-09 14:24 UTC, paulmskim requested changes
A couple small things. Also, it's probably fine, but could you add an artifact of what an unfocused multiline description looks like?

2021-04-09 14:24 UTC, paulmskim commented on src/modules/blocks/rsvp/container-header/style.pcss
> +		line-height: 1.38;
got an empty line here. also double declaration of font size and line height?

2021-04-09 14:24 UTC, paulmskim commented on src/modules/blocks/ticket/container-header/description/style.pcss
> +		&:focus {
does this need a hover style too?

2021-04-12 12:58 UTC, juanfra commented
Thanks @paulmskim - Submitted the changes.

The artifact for that can be found here: https://www.loom.com/share/c3c3fb6a9cf5484c9cdbdc14f2ae7ff6

Please let me know if there's something else missing.

2021-04-12 17:03 UTC, sc0ttkclark commented on readme.txt
> +* Fix - Fixed an issue where long descriptions were breaking the block for the Tickets and RSVP blocks. It's now using auto-size textarea. [ET-1078]
```suggestion
* Fix - Fixed an issue with Tickets and RSVP blocks where long descriptions were breaking the block. They now use an auto-resizing textarea. [ET-1078]
```

2021-04-12 17:04 UTC, sc0ttkclark approved these changes

2021-04-12 17:30 UTC, paulmskim commented
@juanfra awesome, yeah that was exactly what i was looking for, when the rsvp/ticket wasn't in edit state and showed the condensed view. Thanks!

2021-04-12 17:30 UTC, paulmskim approved these changes

2021-04-12 17:40 UTC, merged