Fix/et 1134 email from displays encoded html entities
the-events-calendar/event-tickets pull request #2025
Opened 2021-06-21 15:53 UTC by redscar

### 🎫 Ticket

[ET-1134] 

### 🗒️ Description

Single quotes were being escaped. Gmail did not like this. I removed the escaping that was occurring on the persons name

Bug Fix -

Single line change for TC sending emails for Paypal.

### 🎥 Artifacts 

https://user-images.githubusercontent.com/12241059/122456218-4e81f980-cf7b-11eb-86c5-d9eb7d700884.mp4

### ✔️ Checklist
- [x] I've included a changelog entry both in readme.txt and changelog.txt fi>
- [x] My code is tested. <!-- Check that tests are passing and DO NOT merge i>
- [x] My code has [proper inline documentation](https://the-events-calendar.g>

[ET-1134]: https://theeventscalendar.atlassian.net/browse/ET-1134

2021-06-23 08:35 UTC, juanfra commented
@redscar looks like we need to update the base branch for this PR

2021-06-23 12:30 UTC, redscar commented
@juanfra I just updated the branch to carnotaurus

2021-06-25 09:20 UTC, juanfra requested changes

2021-06-25 09:20 UTC, juanfra commented on changelog.txt
> +* Fix - Prevent Tribe Commerce 'Confirmation email sender name' from displaying improperly when a single quote is added. [ET-1134]
Let's use double quotes and move it to the right version (Below [5.1.5])
```suggestion
* Fix - Prevent Tribe Commerce "Confirmation email sender name" from displaying improperly when a single quote is added. [ET-1134]
```

2021-06-25 09:20 UTC, juanfra commented on readme.txt
> +* Fix - Prevent Tribe Commerce 'Confirmation email sender name' from displaying improperly when a single quote is added. [ET-1134]
```suggestion
* Fix - Prevent Tribe Commerce "Confirmation email sender name" from displaying improperly when a single quote is added. [ET-1134]
```
Let's use double quotes.

2021-06-28 11:45 UTC, juanfra approved these changes

2021-06-28 16:24 UTC, merged