Tweak/etp 702 hide edit column on print
the-events-calendar/event-tickets pull request #2034
Opened 2021-07-13 14:46 UTC by redscar

### 🎫 Ticket

[ETP-702] 

### 🗒️ Description

Removed the Edit column from displaying when printing and updated the column count for resizing the table when printing.

Added class to the printer styles for hiding columns

### 🎥 Artifacts 

![image](https://user-images.githubusercontent.com/12241059/125472161-b2976421-df56-4f33-aa28-fb3deb59d215.png)

### ✔️ Checklist
- [x] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-07-15 18:44 UTC, bordoni submitted a review, later dismissed

2021-07-20 14:32 UTC, juanfra requested changes
Can we have a screencast as artifacts? Switching the columns we have on that view, by enabling/disabling them on the "Screen options" section? (top right part of the screen). I think there's also a merge conflict on the readme.

2021-07-20 14:32 UTC, juanfra commented on readme.txt
> +* Tweak - Removed the edit column when printing the Attendees list. [ETP-ETP-702]
```suggestion
* Tweak - Removed the edit column when printing the Attendees list. [ETP-702]
```
The ID of the ticket has duplicated contents.

2021-07-20 17:44 UTC, juanfra approved these changes

2021-07-20 17:44 UTC, juanfra commented on readme.txt
> +=======
We need to remove these two lines.

2021-07-20 17:44 UTC, juanfra commented on readme.txt
> +
We shouldn't add this new blank line here.

2021-07-23 16:45 UTC, bordoni requested changes

2021-07-23 16:45 UTC, bordoni commented on readme.txt
> +=======
We still need to remove this `======`

2021-07-23 16:57 UTC, bordoni approved these changes

2021-07-23 16:58 UTC, merged