[ET-1145] Feature/et 1145 add export button attendees title
the-events-calendar/event-tickets pull request #2037
Opened 2021-07-21 14:41 UTC by redscar

### 🎫 Ticket

[ET-1145] 

### 🗒️ Description

- Added the export button next to the page title on the Attendees page
- Updated the action `tribe_report_page_after_text_label` to include `$attendees` variable
- Moved the export button generating script to it's own function so it can be reused

### 🎥 Artifacts 

Showing export button next to page title
![image](https://user-images.githubusercontent.com/12241059/126507583-1d93ad9d-1b0f-407a-a5a1-0fad8cea9892.png)
Showing export button on table
![image](https://user-images.githubusercontent.com/12241059/126507663-6edf7844-8e67-433b-a0c0-2ddc30a1f763.png)
Showing no export button with no attendees
![image](https://user-images.githubusercontent.com/12241059/126507883-40cf7aaa-700b-4617-b18c-06056b10f9b3.png)

### ✔️ Checklist
- [x] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-07-21 16:49 UTC, juanfra requested changes

2021-07-21 16:49 UTC, juanfra commented on readme.txt
> +6
This `6` should be an empty line.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +
We shouldn't be introducing blank lines here.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +	 *
Let's remove one empty line here.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +	 * Generate the export URL for exporting attendees
The docblock must have a full stop
```suggestion
	 * Generate the export URL for exporting attendees.
```

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +	public function get_export_url (){
```suggestion
	public function get_export_url() {
```
We need to fix the spacing here.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +	 * @param Tribe__Tickets__Attendees $attendees
Let's add a description for these two parameters.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +	}
Let's have an empty line between the closure and the docblock.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +		// Bail early if there are no attendees
Comments must end with full stop.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +		// Bail early if user is not owner/have permissions
Comments must end with full stop.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +		echo sprintf( '<a target="_blank" href="%s" class="export action page-title-action">%s</a>', esc_url( $export_url = $this->get_export_url() ), esc_html__( 'Export', 'event-tickets' ) ) ;
For security issues we must have `rel="noopener noreferrer"` when the `target` is `_blank`

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees.php
> +		echo sprintf( '<a target="_blank" href="%s" class="export action page-title-action">%s</a>', esc_url( $export_url = $this->get_export_url() ), esc_html__( 'Export', 'event-tickets' ) ) ;
We could possibly split this into multiple lines for better readability.

2021-07-21 16:49 UTC, juanfra commented on src/Tribe/Attendees_Table.php
> +				'export' => sprintf( '<a target="_blank" href="%s" class="export button action">%s</a>', esc_url( tribe( 'tickets.attendees' )->get_export_url() ), esc_html__( 'Export', 'event-tickets' ) ),
For security issues we must have `rel="noopener noreferrer"` when the `target` is `_blank`

2021-07-22 15:54 UTC, paulmskim commented on src/Tribe/Attendees.php
> +
```suggestion
		echo sprintf(
			'<a target="_blank" href="%s" class="export action page-title-action" rel="noopener noreferrer">%s</a>',
			esc_url( $export_url = $this->get_export_url() ),
			esc_html__( 'Export', 'event-tickets' )
		) ;
```

2021-07-22 15:55 UTC, juanfra requested changes
One last minor thing! We're almost there!

2021-07-22 15:55 UTC, juanfra commented on src/admin-views/attendees.php
> +			 * @param Tribe__Tickets__Attendees @attendees The attendees object.
```suggestion
			 * @param Tribe__Tickets__Attendees $attendees The attendees object.
```

2021-07-23 16:41 UTC, bordoni approved these changes

2021-07-23 16:41 UTC, merged