[ET-1107] Add delete functionality for the tickets area in the classic editor.
the-events-calendar/event-tickets pull request #2038
Opened 2021-07-22 14:29 UTC by juanfra

### 🎫 Ticket

[ET-1107] 

### 🗒️ Description

- Adding the delete functionality for the list of tickets in the classic editor.
- Hooking onto existing functionality, keeping the classes and such so the JS works out of the box. We could possibly improve this in the future.

### 🎥 Artifacts 

https://www.loom.com/share/1601bd8ecf75476e8b64a7972c4d4b01

### ✔️ Checklist
- [x] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-07-22 16:02 UTC, paulmskim requested changes

2021-07-22 16:02 UTC, paulmskim commented on src/resources/postcss/tickets-tables.pcss
> +			&::before {
for `:before` and `:after` we use single-colon notation. when the linter is in place, this will be flagged.

```suggestion
			&:before {
```

2021-07-22 16:02 UTC, paulmskim commented on src/resources/postcss/tickets-tables.pcss
> +			font-size: 0;
you already have `font-size: 0` defined just above

2021-07-23 14:47 UTC, paulmskim commented on src/resources/postcss/tickets-tables.pcss
> +			&::before {
still missing this one

2021-07-23 14:48 UTC, paulmskim commented on src/resources/postcss/tickets-tables.pcss
> +			&::before {
might as well combine it with the `.ticket_delete_text` above.

2021-07-23 16:39 UTC, bordoni submitted a review, later dismissed

2021-07-26 15:02 UTC, paulmskim approved these changes

2021-07-26 15:39 UTC, merged