[ET-1064] Display TC pages with post status
the-events-calendar/event-tickets pull request #2068
Opened 2021-08-27 14:05 UTC by juanfra

### 🎫 Ticket

[ET-1064] 

### 🗒️ Description

- Adding reference to our TC pages on the page list.

### 🎥 Artifacts 

https://www.loom.com/share/5e22fab6a68f464eb3db253013e0bbe9

### ✔️ Checklist
- [ ] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [ ] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1064]: https://theeventscalendar.atlassian.net/browse/ET-1064

2021-08-28 04:12 UTC, bordoni requested changes
Just a minor thing, so that we avoid logic on the Hooks class.

2021-08-28 04:12 UTC, bordoni commented on src/Tickets/Commerce/Hooks.php
> +		}
Move this one into a method in the actual Checkout Class and call it here, so we dont have any logic on on Hooks class.

2021-08-28 04:12 UTC, bordoni commented on src/Tickets/Commerce/Hooks.php
> +		}
Move this one into a method in the actual Success Class and call it here, so we dont have any logic on on Hooks class.

2021-08-30 16:47 UTC, paulmskim commented on src/Tickets/Commerce/Checkout.php
> +	 */
add return to docblock

2021-08-30 16:47 UTC, paulmskim commented on src/Tickets/Commerce/Hooks.php
> +	 */
add return to docblock

2021-08-30 16:47 UTC, paulmskim commented on src/Tickets/Commerce/Success.php
> +	 */
add return to docblock

2021-09-01 16:44 UTC, paulmskim approved these changes

2021-09-08 10:33 UTC, merged