[GTRIA-655] Removed style causing overlapping text
the-events-calendar/event-tickets pull request #2070
Opened 2021-08-31 16:52 UTC by redscar

Removed extra CSS that were causing text to overlap when the description was show in the AR modal
`
		@media (--viewport-medium) {
			-ms-grid-row: 3;
			grid-row: 3;
		}

### 🎫 Ticket

[GTRIA-655]  

### 🗒️ Description

### 🎥 Artifacts 

![image](https://user-images.githubusercontent.com/12241059/131543831-3c493777-8fa5-44ff-9b27-b329f678b479.png)
![image](https://user-images.githubusercontent.com/12241059/131543905-21bdf512-8368-49fe-b76d-68de6b6f7644.png)

### ✔️ Checklist
- [ ] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-09-08 22:05 UTC, rafsuntaskin requested changes
Missing ticket entry for readme. Nice work 🥇

2021-09-08 22:05 UTC, rafsuntaskin commented on readme.txt
> +* Fix - Fixed text overlapping description in the ticket AR modal.
```suggestion
* Fix - Fixed text overlapping description in the ticket AR modal. [ET-1179]
```

2021-09-09 10:39 UTC, bordoni submitted a review, later dismissed

2021-09-09 10:58 UTC, juanfra reviewed
The code we're removing is related to the tickets block, for the responsive styles particularly. Have we checked the effect of this on the responsive view for the tickets block? 

I'm not sure that by removing this we're gonna be removing something that we don't want to remove from the tickets block. In any case, if we need a special treatment for the `tribe-tickets-attendees-list-optout--wrapper` inside the modal, we could be adding the exception on the ET+ stylesheet.

2021-09-09 16:03 UTC, juanfra commented
@redscar thanks for checking into that! What I mean with the tickets block is this: https://cloudup.com/cAWraJz__Hq - We're touching code that's specifically for that component, to fix something that we identified on ET+ (the modal).

So, what I was saying is that we should be checking the tickets block with these changes because possibly the way that the checkbox looks there could be affected without that CSS. It's a possibility, but I'm definitely not certain. If the changes we're adding here affect the tickets block we should roll back and add some CSS exception for the modal in ET+.

2021-09-09 16:48 UTC, redscar commented
@juanfra Thanks for clarifying.  I just checked again locally and everything looks good.

![image](https://user-images.githubusercontent.com/12241059/132728313-81832824-3543-462d-bba2-3a7fa24609fc.png)


![image](https://user-images.githubusercontent.com/12241059/132728356-582d1a89-a4ff-42f8-869c-29d7ce0eceec.png)

2021-09-14 09:54 UTC, juanfra commented
@redscar thanks for sharing those! All good then

2021-09-14 09:55 UTC, juanfra approved these changes
⚡

2021-09-15 13:30 UTC, merged