Flush transients whens saving plugin options
the-events-calendar/event-tickets pull request #2179
Opened 2021-11-01 20:39 UTC by moraleida

### 🎫 Ticket

[ET-1287] 

### 🗒️ Description

Flushes the transients whenever the Sandbox option is toggled on/off.

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] I've included a changelog entry both in readme.txt and changelog.txt files. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2021-11-01 21:04 UTC, bordoni requested changes

2021-11-01 21:04 UTC, bordoni commented on src/Tickets/Commerce/Hooks.php
> +		return $options;
Invert the logic. to avoid indentation.

2021-11-01 21:07 UTC, rafsuntaskin commented
As this is related to PayPal gateway specifically. We should move the method into: `wp-content/plugins/event-tickets/src/Tickets/Commerce/Gateways/PayPal/Settings.php` and then Hook from `wp-content/plugins/event-tickets/src/Tickets/Commerce/Gateways/PayPal/Hooks.php`.

2021-11-01 22:24 UTC, moraleida commented on src/Tickets/Commerce/Hooks.php
> +		return $options;
done.

2021-11-01 22:25 UTC, moraleida commented
> Maybe as this is related to PayPal gateway specifically. We should move the method into: `wp-content/plugins/event-tickets/src/Tickets/Commerce/Gateways/PayPal/Settings.php` and then Hook from `wp-content/plugins/event-tickets/src/Tickets/Commerce/Gateways/PayPal/Hooks.php`.

God thinkning. I've moved the method into `Gateway\PayPal\Hooks.php`. Not sure if we need a new method in `Settings` though because all this filter is doing is calling a method of `Signup`, so no real functionality implemented in the `Hooks` file. Let me know what you think @rafsuntaskin

2021-11-01 22:35 UTC, bordoni commented
I would rather see it on the Signup class instead of the settings one.

2021-11-02 00:14 UTC, bordoni approved these changes

2021-11-02 00:18 UTC, merged