[WIP] Admin menu and pages > Tickets menu
the-events-calendar/event-tickets pull request #2228
Opened 2021-12-22 20:14 UTC by juanfra

### 🎫 Ticket

N/A 

### 🗒️ Description

- Implementation of top of https://github.com/the-events-calendar/tribe-common/pull/1691
- Need to implement welcome page for the "Tickets" page.

### Things to do

- [ ] Be sure we have the proper settings in the Tickets menu when ET is working without TEC.

### 🎥 Artifacts 

- Coming soon.

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2022-04-11 15:49 UTC, redscar commented on src/Tribe/Admin/Ticket_Settings.php
> +	 * @param string $footer_text The admin footer text, maybe modified.
Document @return

2022-04-12 14:03 UTC, borkweb requested changes
This is looking pretty sweet!

2022-04-12 14:03 UTC, borkweb commented on src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-connection.php
> +$resync_connection_url = Tribe__Tickets__Main::instance()->settings()->get_url( [
```suggestion
$resync_connection_url = tribe( 'tickets.main' )->settings()->get_url( [
```

2022-04-12 14:03 UTC, borkweb commented on src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-user-info.php
> +$url = Tribe__Tickets__Main::instance()->settings()->get_url( [
```suggestion
$url = tribe( 'tickets.main' )->settings()->get_url( [
```

2022-04-12 20:32 UTC, borkweb approved these changes

2022-04-12 21:54 UTC, borkweb requested changes
Ah, I need to retract my approval - I realized something that needs a bit of a refactor while looking at the TEC implementation. I'm working on a PR for that and then it can be replicated on this PR as well.

2022-04-13 03:50 UTC, borkweb commented
Here's a re-working of the class structure for TEC. We'll need to replicate that for Event Tickets as well: https://github.com/the-events-calendar/the-events-calendar/pull/3813

2022-04-13 09:40 UTC, juanfra commented
@borkweb excellent, thanks! [Here's a commit with those changes for ET](https://github.com/the-events-calendar/event-tickets/pull/2228/commits/75ea73ca55c365e2fdd61a83d4c61fd8636fb495).

I went ahead and renamed the class to `Tickets_Settings` ([related to this comment](https://github.com/the-events-calendar/the-events-calendar/pull/3813#discussion_r849217178)), as it makes more sense and it's more in-line with our naming conventions.

2022-04-13 12:50 UTC, borkweb requested changes

2022-04-13 12:50 UTC, borkweb commented on src/Tribe/Admin/Tickets_Settings.php
> +class Tickets_Settings {
This should be `Ticket_Settings` - See my comment [here](https://github.com/the-events-calendar/the-events-calendar/pull/3813/files#r849440547) for a bit more info.

2022-04-13 18:55 UTC, borkweb commented on src/Tribe/Admin/Tickets_Settings.php
> +class Tickets_Settings {
Revising based on our conversation in Slack and the resulting update to TEC - change to `src/Tribe/Admin/Settings.php`

2022-04-14 12:56 UTC, borkweb approved these changes

2022-04-14 15:32 UTC, merged