[ETP-497] Fixed Shared capacity data when ticket capacity is updated
the-events-calendar/event-tickets pull request #2233
Opened 2022-01-06 16:22 UTC by rafsuntaskin

### 🎫 Ticket

[ETP-497] 

### 🗒️ Description

* If there were tickets created with the shared capacity it stored the shared cap data properly, but if the tickets were switched back to regular stock then it was not clearing up the Shared stock data. This is fixed now so that toggling shared capacity will reflect the Event capacity properly.

### 🎥 Artifacts 
🎥 screencast: https://d.pr/v/YB1vWw

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ETP-497]: https://theeventscalendar.atlassian.net/browse/ETP-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-01-06 16:37 UTC, redscar approved these changes

2022-01-07 22:27 UTC, codingmusician submitted a review, later dismissed

2022-01-10 18:35 UTC, bordoni requested changes

2022-01-10 18:35 UTC, bordoni commented on src/Tribe/Tickets_Handler.php
> +		$ticket_capacity      = Tribe__Utils__Array::get( $ticket_capacity_data, 'capacity', [] );
If data is invalid, bail with a WP Error.

2022-01-10 19:39 UTC, bordoni approved these changes

2022-01-10 19:45 UTC, merged