[ET-1454] Tickets Commerce - Add New Currencies for Stripe
the-events-calendar/event-tickets pull request #2417
Opened 2022-05-19 14:43 UTC by codingmusician

### 🎫 Ticket

[ET-1454] 

### 🗒️ Description

Adds some new currency codes that are supported by Stripe.

### 🎥 Artifacts 

N/A

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2022-05-19 14:44 UTC, codingmusician commented
PR on hold until `release/G22.leptoceratops` is released and merged into `master`

2022-05-24 18:52 UTC, bordoni requested changes

2022-05-24 18:52 UTC, bordoni commented on src/Tickets/Commerce/Utils/Currency.php
> +		ksort( $map );
Sorting is expensive, do some sort of caching of the value after sorting so that it only sorts once.

2022-05-25 17:43 UTC, rafsuntaskin submitted a review, later dismissed

2022-05-25 18:21 UTC, bordoni commented on src/Tickets/Commerce/Utils/Currency.php
> +		$map = $cache->get( $cache_key );
Dont use `get/set` which will use a transient, go for `tribe( 'cache' )->stripe_default_currency_map` for a in memory cache.

2022-05-26 02:28 UTC, merged