[ET-1456] Tickets Commerce - Add New Currencies for Stripe
the-events-calendar/event-tickets pull request #2419
Opened 2022-05-24 16:05 UTC by codingmusician

### 🎫 Ticket

[ET-1456] 

### 🗒️ Description

Adds some new currency codes that are supported by Stripe

### 🎥 Artifacts 

N/A

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1456]: https://theeventscalendar.atlassian.net/browse/ET-1456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-05-24 18:52 UTC, bordoni submitted a review, later dismissed

2022-05-25 12:08 UTC, rafsuntaskin approved these changes

2022-05-26 14:31 UTC, bordoni approved these changes

2022-05-26 14:31 UTC, redscar approved these changes

2022-05-26 14:34 UTC, moraleida requested changes
some string consistency comments

2022-05-26 14:34 UTC, moraleida commented on src/Tickets/Commerce/Utils/Currency.php
> +				'name'                  => __( 'Sol (PEN)', 'event-tickets' ),
Peruvian Sol?

2022-05-26 14:34 UTC, moraleida commented on src/Tickets/Commerce/Utils/Currency.php
> +				'name'                  => __( 'Paraguayan guaraní (PYG)', 'event-tickets' ),
Paranguaian guaraní

2022-05-26 17:08 UTC, moraleida approved these changes

2022-05-26 17:28 UTC, merged