Fix WIP, filtering event IDs.
the-events-calendar/event-tickets pull request #2538
Opened 2023-01-20 01:25 UTC by stratease

### 🎫 Ticket

[TICKET_ID] 

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2023-01-24 03:09 UTC, Camwyn requested changes
Translated strings need some love.

2023-01-26 16:57 UTC, Camwyn approved these changes

2023-01-26 17:22 UTC, rafsuntaskin approved these changes

2023-01-26 17:35 UTC, juanfra approved these changes
Looking good, we should ask QA to test this one with ET as standalone as well. @stratease can you please add it to the testing instructions in the jira ticket?

2023-01-26 17:36 UTC, merged