[ETP-860] - Enhancement - Add ticket restock functionality upon attendee deletion for TicketsCommerce
the-events-calendar/event-tickets pull request #2584
Opened 2023-03-21 12:52 UTC by rafsuntaskin

### 🎫 Ticket

[ETP-860] 

### 🗒️ Description

* Properly restock Tickets Commerce tickets after deleting corresponding attendee.

### 🎥 Artifacts 
🎥 screencast(s): https://share.cleanshot.com/4Z4m7k5w

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ETP-860]: https://theeventscalendar.atlassian.net/browse/ETP-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-22 18:35 UTC, codingmusician commented on src/Tickets/Commerce/Module.php
> +		return false;
Bail early if false
```suggestion
		if ( ! $deleted ) {
			return false;
		}
		
		// Run anything we might need on parent method.
		parent::delete_ticket( $event_id, $ticket_id );
		return true;
```

2023-03-22 18:50 UTC, codingmusician commented on tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php
> +		$this->assertEquals( 1, $new_count, 'There should be 4 attendees' );
```suggestion
		$this->assertEquals( 1, $new_count, 'There should be 1 attendee' );
```

2023-03-22 18:53 UTC, rafsuntaskin commented on src/Tickets/Commerce/Hooks.php
> +		add_action( 'tec_tickets_commerce_attendee_before_delete', [ $this, 'update_stock_after_attendee_deletion' ] );
These are Tickets Commerce hooks only, so won't impact any TribeCommerce users. It was here without any impact.

2023-03-22 19:05 UTC, bordoni requested changes

2023-03-22 19:05 UTC, bordoni commented on src/Tickets/Commerce/Hooks.php
> +		$this->container->make( Ticket::class )->update_stock_after_attendee_deletion( $attendee_id );
We can't just delete a method like that when it's public, move it to the end and deprecate it properly.

2023-03-23 15:03 UTC, codingmusician submitted a review, later dismissed

2023-03-23 18:31 UTC, rafsuntaskin commented on src/Tickets/Commerce/Attendee.php
> +		\Tribe__Post_Transient::instance()->delete( $event_id, \Tribe__Tickets__Tickets::ATTENDEES_CACHE );
Moved under deletion handler.

2023-03-24 19:47 UTC, codingmusician approved these changes

2023-03-24 19:51 UTC, merged