WIP: Tickets Emails - Dynamizing Attendees & Improving Placeholders
the-events-calendar/event-tickets pull request #2611
Opened 2023-04-21 23:47 UTC by codingmusician

### 🗒️ Description

This is a WIP. We need to dynamize the attendee data for the Completed Order, Failed Order and Purchase Receipt emails. I also realized that placeholders weren't being set in the preview data, so I'm also working on enhancing that experience so the template more reflect real-life data.

### 🎥 Artifacts 

N/A

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2023-04-23 02:55 UTC, bordoni requested changes

2023-04-23 02:55 UTC, bordoni commented on src/Tickets/Emails/Email/Ticket.php
> +			$this->get_heading();
We should avoid ternaries like this.

2023-04-27 17:38 UTC, codingmusician commented
To Do: Need to update all references to `__set()` and `__get()` once #2615 is merged.

2023-04-27 19:29 UTC, bordoni commented
You can update the `__set()` and `__get()` refs, it's merged.

2023-04-27 21:13 UTC, codingmusician commented
Still a WIP: There's currently a discrepancy between the `tickets` data that get passed into `Ticket` email versus the other emails.

2023-04-28 20:06 UTC, redscar commented
Looks like one of the tests are failing

2023-04-28 20:09 UTC, bordoni submitted a review, later dismissed

2023-05-01 18:16 UTC, merged