Tickets Emails: DQA Modifications
the-events-calendar/event-tickets pull request #2634
Opened 2023-05-11 19:20 UTC by codingmusician

### 🎫 Ticket

n/a

### 🗒️ Description

These are changes that came out of the most recent DQA for Tickets Emails.

### 🎥 Artifacts 

Figma Link: https://www.figma.com/file/NMNsb2M0UtblU9n1C99q9T/Admin---Tickets-%2F-Emails?type=design&node-id=1138%3A231&t=7vCjXoXwzScwuAm8-1

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2023-05-11 23:44 UTC, bordoni approved these changes

2023-05-13 00:58 UTC, bordoni commented
Make sure you fix the snapshot tests.

2023-05-15 18:41 UTC, bordoni requested changes
We need artifacts here too.

2023-05-15 18:56 UTC, codingmusician commented
> We need artifacts here too.

Updated artifacts and snapshots

2023-05-15 20:04 UTC, redscar approved these changes

2023-05-15 21:33 UTC, bordoni approved these changes

2023-05-15 21:46 UTC, merged