[ET-1767] Attendee Registration Loop issue on certain themes.
the-events-calendar/event-tickets pull request #2674
Opened 2023-06-01 14:25 UTC by redscar

### 🎫 Ticket

[ET-1767] 

### 🗒️ Description

When using Astra theme, the attendee registration form on the attendee registration page is being generated infinite times(on loop), and the page keeps loading. This issue seems to mostly occur with Astra version 4.x.  

Mike found the original snippet that I have used https://gist.github.com/codingmusician/da909aa95bc08e80baaab3456f586014. 

### 🎥 Artifacts 

Original Issue - 
![image](https://github.com/the-events-calendar/event-tickets/assets/12241059/8d38e85d-f66b-46bb-be7b-b859058d073c)

Fixed -

![image](https://github.com/the-events-calendar/event-tickets/assets/12241059/4b96a5ba-5394-4fa5-b6f1-251e71ceaf5f)

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1767]: https://theeventscalendar.atlassian.net/browse/ET-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-01 18:26 UTC, rafsuntaskin commented
@redscar Attendee registration is part of ETP. Can we add this filter into ETP?

2023-06-01 18:32 UTC, juanfra requested changes
I think we can avoid re-filtering this and setting the `is_singular` to true [here](https://github.com/the-events-calendar/event-tickets/blob/afaf3197d94b8022b150c1d43b4672b2e7db33fa/src/Tribe/Attendee_Registration/Template.php#L84).

All the conditionals that you're applying on `tec_tickets_mock_ar_as_singular ` made sense on a snippet (where maybe we used them as safe checks), but many of those are not really useful there (checking if ET is active in ET for example).

2023-06-01 18:46 UTC, redscar commented
> I think we can avoid re-filtering this and setting the `is_singular` to true [here](https://github.com/the-events-calendar/event-tickets/blob/afaf3197d94b8022b150c1d43b4672b2e7db33fa/src/Tribe/Attendee_Registration/Template.php#L84).
> 
> All the conditionals that you're applying on `tec_tickets_mock_ar_as_singular ` made sense on a snippet (where maybe we used them as safe checks), but many of those are not really useful there (checking if ET is active in ET for example).

@juanfra Good call. By making that change it seems the issue is still fixed and working properly.

2023-06-01 18:48 UTC, codingmusician approved these changes

2023-06-02 09:01 UTC, juanfra approved these changes

2023-06-02 12:38 UTC, merged