Address some PHP 8.1 deprecation notices around matching signatures a…
the-events-calendar/event-tickets pull request #2723
Opened 2023-07-18 21:23 UTC by Camwyn

…nd serialization functions.

### 🎫 Ticket

[TICKET_ID] 

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [X] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [X] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2023-07-31 17:03 UTC, stratease requested changes

2023-07-31 17:03 UTC, stratease commented on readme.txt
> +* Tweak - Remove some PHP 8.1 deprecation warnings. [TBD]
```suggestion
* Tweak - Remove some PHP 8.1 deprecation warnings. [ET-1830]
```

2023-07-31 17:05 UTC, stratease commented
I'm wondering if we defer adding tests to PHPStan lint tests as the test mechanism for this. That ought to add coverage for this particular serialization deprecation warning.

2023-08-01 14:49 UTC, Camwyn commented
> I'm wondering if we defer adding tests to PHPStan lint tests as the test mechanism for this. That ought to add coverage for this particular serialization deprecation warning.

That sounds reasonable

2023-08-01 15:56 UTC, stratease approved these changes

2023-08-02 11:54 UTC, merged