[ET-1935] PHP 8+ compatibility for Implode in REST Endpoint
the-events-calendar/event-tickets pull request #2850
Opened 2023-11-21 19:14 UTC by redscar

### 🎫 Ticket

[ET-1935] 

### 🗒️ Description

Fixed compatability issue with php 8+.

2023-11-22 11:34 UTC, juanfra reviewed
Looking good, one minor adjustment to the readme entry.

2023-11-22 11:34 UTC, juanfra commented on readme.txt
> +* Tweak -  Prevented Single Attendee endpoint from throwing a notice on PHP 8+.
Let's add the ticket ID to the readme entry.

2023-11-22 14:42 UTC, juanfra approved these changes

2023-11-22 16:42 UTC, bordoni requested changes

2023-11-22 16:42 UTC, bordoni commented on readme.txt
> +* Tweak -  Prevented Single Attendee endpoint from throwing a notice on PHP 8+. [ET-1935]
```suggestion
* Tweak - Prevented Single Attendee endpoint from throwing a notice on PHP 8+. [ET-1935]
```

2023-11-27 16:19 UTC, codingmusician approved these changes

2023-11-27 17:00 UTC, rafsuntaskin approved these changes

2023-11-27 18:24 UTC, merged