[ET-1949] Resolve `offsetGet` deprecation warnings
the-events-calendar/event-tickets pull request #2866
Opened 2023-12-06 20:40 UTC by codingmusician

### 🎫 Ticket

[ET-1949] 

### 🗒️ Description

Since PHP 8.1, there has been a Deprecation warning that is logged whenever you visit an event list (back end events or front end calendar).

```PHP Deprecated:  Return type of Tribe\Tickets\Events\Views\V2\Models\Tickets::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/wordpress/wp-content/plugins/event-tickets/src/Tribe/Events/Views/V2/Models/Tickets.php on line 242```

The issue is resolved when adding the `mixed` return type to the method.

### 🎥 Artifacts 

N/A

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1949]: https://stellarwp.atlassian.net/browse/ET-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-07 19:29 UTC, Camwyn requested changes

2023-12-07 19:29 UTC, Camwyn commented on src/Tribe/Events/Views/V2/Models/Tickets.php
> +	public function offsetGet( $offset ): mixed {
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.composite.redundant

You can't use "mixed" here. Use `#[\ReturnTypeWillChange]` in the docblock.

2023-12-20 21:29 UTC, estebanhdzc approved these changes
Nicely done!

2023-12-21 14:49 UTC, Camwyn approved these changes

2023-12-21 15:42 UTC, merged