Updated DocBlocks to correct template override location (tribe vs tri…
the-events-calendar/event-tickets pull request #2900
Opened 2024-01-18 00:15 UTC by sdokus

…be-events)

### 🎫 Ticket

[GTRIA-1170] 

### 🗒️ Description

Updated the template paths in the DocBlocks for all the files in `src/views/tickets`. The path was previously `[your-theme]/tribe-events/[...]` but it should be `[your-theme]/tribe/[...]`

### ✔️ Checklist
- [X] I've included a changelog entry in the readme.txt file. 
- [X] My code is tested. 
- [X] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2024-01-18 12:05 UTC, juanfra requested changes
Thanks @sdokus!

Whenever you're updating templates, you'll need to set the `@version TBD` and `@since TBD Description of the changes you have done`.

That way the system makes the interpretation of the latest version and warns users of templates with changes in the `Recent template changes` of the `Troubleshooting` page.

2024-02-01 19:30 UTC, bordoni submitted a review, later dismissed

2024-02-02 13:51 UTC, juanfra requested changes
Thanks for working on this, Sam! I left a few minor comments for the readme and we are good to go

2024-02-02 13:51 UTC, juanfra commented on readme.txt
> += [TDB] =
```suggestion

= [TBD] TBD =

```

2024-02-02 13:51 UTC, juanfra commented on readme.txt
> +* Tweak - Changed incorrect file paths in DocBlocks for template overrides for all files in src/views/tickets. [GTRIA-1170]
```suggestion
* Tweak - Changed incorrect file paths in DocBlocks for template overrides for all files in `src/views/tickets`. [ET-2004]
```

2024-02-14 13:50 UTC, redscar commented
This looks good. I would update the branch to point to G24.boxer and you should be good to go.

2024-04-03 16:25 UTC, codingmusician approved these changes

2024-04-03 16:26 UTC, juanfra approved these changes

2024-04-03 16:26 UTC, merged