Fix - Removed strict type casting from signature to avoid fatals with external filtered values.
the-events-calendar/event-tickets pull request #2909
Opened 2024-01-24 15:09 UTC by rafsuntaskin

### 🎫 Ticket

[TICKET_ID] 

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

2024-01-24 15:15 UTC, lucatume requested changes

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	public function filter_start_date_for_series( string $start_date, WP_Post $series, $display_time, $date_format ): string {
I would remove the assumption the `start_date` parameter is a `string` as well.

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	 * @param mixed   $display_time Whether to display the time.
I would not change the types in the doc-block: they represent what is _ideally_ expected.

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	public function filter_start_date_for_series( string $start_date, WP_Post $series, $display_time, $date_format ): string {
Default all parameters to `null`

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +									->order_by( 'event_date', 'ASC' )
???

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	 * @param mixed   $display_time Whether to display the time.
Do not change the types in the doc-block.

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	public function filter_end_date_for_series( string $end_date, WP_Post $series, $display_time, $date_format ): string {
Remove the `string` type-hint from the `$end_date` parameter.

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	public function filter_end_date_for_series( string $end_date, WP_Post $series, $display_time, $date_format ): string {
In the methods, make sure the values are of the expected type, else bail out.

2024-01-24 15:15 UTC, lucatume commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +	public function filter_start_date_for_series( string $start_date, WP_Post $series, $display_time, $date_format ): string {
In the method, make sure the parameters are of the expected type, else bailout.

2024-01-24 15:17 UTC, rafsuntaskin commented on src/Tickets/Flexible_Tickets/Series_Passes/Base.php
> +									->order_by( 'event_date', 'ASC' )
phpcbf -_-

2024-01-25 09:23 UTC, lucatume approved these changes

2024-01-29 17:39 UTC, redscar approved these changes

2024-01-29 17:39 UTC, merged