WooCommerce HPOS Issue - Added filter to extend WooCommerce URL.
the-events-calendar/event-tickets pull request #2916
Opened 2024-01-30 20:23 UTC by redscar

Added a new filter so that WooCommerce can hook into and add the proper URL.

https://github.com/the-events-calendar/event-tickets-plus/pull/1519

2024-01-30 20:33 UTC, bordoni commented on src/Tribe/Attendees_Table.php
> +			'tec_attendees_table_order_id_url',
`tec_tickets_` is the correct prefix.

2024-01-30 20:33 UTC, bordoni requested changes
Changelog?

2024-01-30 20:33 UTC, bordoni commented on src/Tribe/Attendees_Table.php
> +			// @todo fix this piece
What is this todo?

2024-01-30 23:19 UTC, codingmusician approved these changes

2024-01-31 05:44 UTC, rafsuntaskin commented
This filter is not needed, we should include the data within the WooCommerce Provider `get_attendee` method as we do for the [EDD](https://github.com/the-events-calendar/event-tickets-plus/blob/fc988a79ede9ceb0095b370ac4b8185fd51c00b4/src/Tribe/Commerce/EDD/Main.php#L1595).

2024-01-31 05:44 UTC, rafsuntaskin requested changes
This filter is not needed, we should include the data within the WooCommerce Provider `get_attendee` method as we do for the [EDD](https://github.com/the-events-calendar/event-tickets-plus/blob/fc988a79ede9ceb0095b370ac4b8185fd51c00b4/src/Tribe/Commerce/EDD/Main.php#L1595).

2024-01-31 16:48 UTC, redscar commented
Closing this ticket due to it not being needed for the Woocommerce work. 

https://github.com/the-events-calendar/event-tickets-plus/pull/1519/files#diff-cb640b1c62c1053fc7d6483c39896d9d7559ed05cb62e2585558aaf422ee936bR2507

2024-01-31 16:48 UTC, closed without merging