[ET-2018] Classic Editor > ECP upsell showing when it should not
the-events-calendar/event-tickets pull request #2950
Opened 2024-03-05 15:49 UTC by codingmusician

### 🎫 Ticket
[ET-2018]

### 🗒️ Description
The ECP upsell (for multiple ticket types) should not be showing when ECP is installed and activated. It should also not be showing when editing a non-event. In both cases, the upsell was showing. This PR adds the logic to fix that.

### 🎥 Artifacts 
https://www.loom.com/share/9515fc37741c4a9f9b730d01984061b0?sid=86937f18-f35c-4548-9456-7888e3b1feed

### ✔️ Checklist
- [x] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [x] Have you added Artifacts?
- [x] Check the base branch for your PR.
- [x] Add your PR to the project board for the release.

2024-03-05 18:18 UTC, redscar commented on src/Tickets/Admin/Upsell.php
> +		// If they already have ECP activated or are not within the admin area, then bail.
We should probably update the `@since`.

2024-03-05 18:22 UTC, rafsuntaskin requested changes
This hook should be unhooked from ECP instead of doing Class_exist checks inside this one.

Or we can use the Flexible Tickets base provider as well as that is only registered when ECP is enabled: https://github.com/the-events-calendar/event-tickets/blob/7927ad86111bc17e3c3fb2c83db53f9abbbd516e/src/Tickets/Flexible_Tickets/Base.php#L95

2024-03-06 21:18 UTC, bordoni submitted a review, later dismissed

2024-03-06 21:18 UTC, bordoni commented on src/Tickets/Admin/Upsell.php
> +		}
I would use an action like `did_action( 'action_that_only_happens_in_pro' )`, that tends to be a safer bet.

2024-03-07 16:22 UTC, codingmusician commented
Added this check, which is an action that runs once within ECP upon `plugins_loaded`:
```did_action( 'tribe_events_pro_init_apm_filters' )```

2024-03-07 16:26 UTC, redscar approved these changes

2024-03-07 16:30 UTC, rafsuntaskin approved these changes

2024-03-07 17:07 UTC, merged