Add variables to docblock
the-events-calendar/event-tickets pull request #3032
Opened 2024-05-02 14:38 UTC by andrasguseo

Variables were missing from the docblock. This likely influenced that our documentation on this filter was incompolete. https://www.dropbox.com/scl/fi/qqgf8qvjetg8inw1bs18b/shot_240502_160124.jpg?rlkey=ctce8mev4d8bp56f75kgxxiu6&dl=0

2024-05-03 01:26 UTC, bordoni requested changes
Add `@since` here if we are making changes.

2024-05-03 09:18 UTC, andrasguseo commented
Added `@since TBD`.
I'm not sure when this filter was introduced though, and adding `@since {upcoming version}` doesn't feel the best, but surely better than nothing.
I'd love to learn how to find when a piece of code was added.

2024-05-07 05:02 UTC, bordoni approved these changes

2024-05-07 11:59 UTC, merged

2024-05-13 16:22 UTC, Camwyn commented
Y'all merged a TBD into master?