Address fields for Stripe payment
the-events-calendar/event-tickets pull request #3125
Opened 2024-07-24 00:28 UTC by pattihis

### 🎫 Ticket

[ETP-934]

### 🗒️ Description

If Stripe is our payment gateway, and if more payment methods than simple Credit Cards are available, then we render a form to collect users address and we pass that to Stripe as billing and shipping data. 

### ✔️ Checklist
- [x] Ran `npm run changelog` to add changelog file(s).
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [x] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [x] Check the base branch for your PR.
- [x] Add your PR to the project board for the release.

2024-07-24 02:10 UTC, borkweb requested changes
Looking good! A couple of tweaks

2024-07-24 02:10 UTC, borkweb commented on src/resources/js/commerce/gateway/stripe/checkout.js
> +		$( obj.selectors.renderButton ).on( 'click', obj.renderPayment );
I know that this is mimicking the line below it, however, it is good practice to bind to the document or a container in the event that the item is injected into the page via lazy loading.

```suggestion
		$( document ).on( 'click', obj.selectors.renderButton, obj.renderPayment );
```

2024-07-24 02:10 UTC, borkweb commented on src/resources/postcss/tickets-commerce/_checkout.pcss
> +		grid-template-columns: 1fr 1fr;
I will _always_ read fr fr as "for real, for real" - hahaha 🤪

2024-07-24 02:10 UTC, borkweb commented on src/views/v2/commerce/checkout/gateways.php
> +if ( ! is_user_logged_in() && $must_login ) {
A micro optimization, but let's move the more expensive item second:

```suggestion
if ( $must_login && ! is_user_logged_in() ) {
```

2024-07-24 02:10 UTC, borkweb commented on src/views/v2/commerce/checkout/purchaser-info.php
> +if ( ! is_user_logged_in() && $must_login ) {
```suggestion
if ( $must_login && ! is_user_logged_in() ) {
```

2024-07-24 02:10 UTC, borkweb commented on src/views/v2/commerce/checkout/purchaser-info.php
> +	if ( 'stripe' === $gateway::get_key() && $gateway::is_enabled() && $gateway::is_active() ) {
Our ~standard~ general practice is to split to multi-lines when the conditionals exceed two for readability:

_Note: I thought I had put that in our standards, but I guess that is something that we don't draw a hard line on, just encourage for readability._

```suggestion
	if (
		'stripe' === $gateway::get_key()
		&& $gateway::is_enabled()
		&& $gateway::is_active()
	) {
```

2024-07-24 02:10 UTC, borkweb commented on src/views/v2/commerce/checkout/purchaser-info.php
> +		if ( 1 < count( $payment_methods ) || ( 1 === count( $payment_methods ) && 'card' !== $payment_methods[0] ) ) {
```suggestion
		if (
			1 < count( $payment_methods )
			|| (
				1 === count( $payment_methods )
				&& 'card' !== $payment_methods[0]
			)
		) {
```

2024-07-24 13:47 UTC, borkweb requested changes
I missed some small grammar changes when I did the review last night 🥼

2024-07-24 13:47 UTC, borkweb commented on src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete/content.php
> +			esc_html__( 'If you use certain payment providers with Stripe including Afterpay, Klarna or Clearpay additional Billing Fields will be displayed at checkout as required by Stripe. %1$sLearn More%2
Small grammar fixes I missed before

```suggestion
			esc_html__( 'If you use certain payment providers with Stripe, including Afterpay, Klarna, or Clearpay, additional Billing Fields will be displayed at checkout as required by Stripe. %1$sLearn More%2$s.', 'event-tickets' ),
```

2024-07-24 13:47 UTC, borkweb commented on src/Tickets/Commerce/Gateways/Stripe/Settings.php
> +			__( '%1$sPayment methods available for %2$s%3$s.<br /><br /> The payment methods listed here are dependent on the currency selected for Tickets Commerce and the currency each payment method suppor
```suggestion
			__( '%1$sPayment methods available for %2$s%3$s.<br /><br /> The payment methods listed here depend on the currency selected for Tickets Commerce and the currency supported by each payment method. If you select a payment provider other than Credit Cards, additional billing information fields will be displayed at checkout as required by Stripe. You can review the payment methods and their availablity for each currency on %4$sStripe\'s documentation%5$s.<br /><br />', 'event-tickets' ),
```

2024-07-24 17:43 UTC, codingmusician commented on src/resources/postcss/tickets-commerce/_checkout.pcss
> +		}
```suggestion
		input::placeholder {
  			color: var(--tec-color-border-tertiary);
  			font-size: var(--tec-font-size-2);
  			opacity: 1;
		}
```

2024-07-24 17:46 UTC, codingmusician submitted a review, later dismissed

2024-07-25 12:13 UTC, borkweb submitted a review, later dismissed

2024-07-25 13:16 UTC, dpanta94 approved these changes

2024-07-25 13:16 UTC, merged