fix blank global modes
the-events-calendar/event-tickets pull request #3145
Opened 2024-08-01 17:41 UTC by codingmusician

### 🎫 Ticket
[ETP-920]

### 🗒️ Description
It was found that using Tickets Commerce and having shared capacity and unlimited capacity ticket on the same event/post, the global stock value was being decreased even when purchasing an unlimited ticket. Global stock should only be decreased on shared capacity tickets. I found that unlimited capacity tickets have their "ticket stock mode" set to either 'own' or a blank string. When a ticket is purchased, we weren't checking for the blank string before updating the global stock.

### 🎥 Artifacts 
[Screencast](https://share.zight.com/2Nu8ng1P)

### ✔️ Checklist
- [ ] Ran `npm run changelog` to add changelog file(s).
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-08-01 18:47 UTC, redscar commented
Looks good, let's update the `@since` on the docblock and should be good to go :+1:

2024-08-01 19:02 UTC, JPry requested changes
I left a comment below, and one other question: What about the `decrease_ticket_sales_by()` method?

2024-08-01 19:16 UTC, codingmusician commented on src/Tickets/Commerce/Ticket.php
> +		if ( ! empty( $shared_capacity ) && 'own' !== $shared_capacity && $global_stock instanceof \Tribe__Tickets__Global_Stock ) {
We're only looking for a string in this case. So if the value were somehow `false` we would also not want to update the global stock.

2024-08-01 19:24 UTC, JPry commented on src/Tickets/Commerce/Ticket.php
> +		if ( ! empty( $shared_capacity ) && 'own' !== $shared_capacity && $global_stock instanceof \Tribe__Tickets__Global_Stock ) {
Sounds good, I just wanted to make sure we were doing the right thing. The `empty()` function can be a bit tricky for things like this, so I wanted to make sure it's what we're expecting.

2024-08-01 19:24 UTC, codingmusician commented
> I left a comment below, and one other question: What about the `decrease_ticket_sales_by()` method?

@JPry This is a good question. Looking at that method, it appears to be only used within the legacy `TribeCommerce` feature, which Tickets Commerce has replaced. I also found a note that the use of this method was removed from TC here: https://github.com/the-events-calendar/event-tickets/blob/07cc67394c9afb2a3af2737878e7a18a2df4be5f/src/Tickets/Commerce/Ticket.php#L1030

2024-08-01 19:25 UTC, redscar approved these changes

2024-08-01 19:33 UTC, JPry approved these changes

2024-08-01 19:33 UTC, merged

2024-08-01 19:35 UTC, Camwyn commented on src/Tickets/Commerce/Ticket.php
> +		if ( ! empty( $shared_capacity ) && 'own' !== $shared_capacity && $global_stock instanceof \Tribe__Tickets__Global_Stock ) {
I'd point out that the [docblock](https://github.com/the-events-calendar/event-tickets/pull/3145/files#diff-960d6af64b1cae0ab20d33a9293a9aa3ae975a624399a539da3c819f31d6089bR900) says `$shared_capacity` is a boolean - not a string.

2024-08-01 21:13 UTC, codingmusician commented on src/Tickets/Commerce/Ticket.php
> +		if ( ! empty( $shared_capacity ) && 'own' !== $shared_capacity && $global_stock instanceof \Tribe__Tickets__Global_Stock ) {
That is a good point. I didn't even notice that. After more research, I found that the only place that this method is being used as a non-boolean value is here: https://github.com/the-events-calendar/event-tickets/blob/db8cb39e11ab7e7f4cdb7f4c18a64cd0167c0103/src/Tickets/Commerce/Flag_Actions/Increase_Sales.php#L68

I'm going to work up a new PR to do the logic in the `Increase_Sales::handle()` method and pass in the `$shared_capacity` param as a boolean value.

2024-08-02 14:29 UTC, Camwyn commented
This was merged into the wrong branch - revert and re-do please.