[ET-2267] Check post status before RSVP
the-events-calendar/event-tickets pull request #3437
Opened 2024-12-02 21:57 UTC by codingmusician

### 🎫 Ticket
[ET-2267]

### 🗒️ Description
We want to ensure that a users cannot register for an RSVP on an unpublished event or post.

### 🎥 Artifacts 
N/A

### ✔️ Checklist
- [ ] Ran `npm run changelog` to add changelog file(s). More info [here](https://docs.theeventscalendar.com/developer/git/changelogs/#process)
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [x] Are all the **required** tests passing?
- [x] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [x] Check the base branch for your PR.
- [x] Add your PR to the project board for the release.

2024-12-02 23:16 UTC, Camwyn approved these changes

2024-12-03 13:11 UTC, dpanta94 requested changes

2024-12-03 13:11 UTC, dpanta94 commented on src/Tribe/RSVP.php
> +		if ( 'publish' !== $post_status ) {
Shouldn't they be able to RSVP for private events for which they have the right to see ? 

Maybe we should check if `current_user_can` instead.

2024-12-03 17:03 UTC, dpanta94 requested changes

2024-12-03 17:32 UTC, dpanta94 approved these changes

2024-12-03 17:52 UTC, dpanta94 approved these changes

2024-12-03 17:54 UTC, merged